// (v0.6.5) PGN Mentor 대회의 개최지 한국어 표기(외래어 표기법 기준 AI 초안 — 검수 필요)와 시리즈 예외.
//  · PLACE_KO: PGN의 Site 도시 이름(국가코드 뗀 것) → 한국어. 없으면 build-pgn-tournaments가 경고로 알려 준다.
//  · PLACE_EN: 철자가 독일어·옛 표기인 Site를 화면용 영어로(Duesseldorf → Düsseldorf …).
//  · SERIES_OVERRIDE: 파일명 접두어(norm)가 도시 이름이 아닌 시리즈(소련 선수권·인터존 등)의 이름·종류.
export const PLACE_EN = { Haag: "The Hague", Zuerich: "Zürich", Duesseldorf: "Düsseldorf", Geneve: "Geneva", Koeln: "Cologne", Swinemuende: "Swinemünde", "Teplitz-Schoenau": "Teplitz-Schönau", "Maehrisch Ostrau": "Mährisch-Ostrau", Naestved: "Næstved", Kiev: "Kyiv", Holland: "Netherlands", "St Louis": "Saint Louis", Caleta: "Gibraltar", Donostia: "San Sebastián", Karlsbad: "Karlovy Vary (Karlsbad)", Merano: "Merano", Meran: "Meran" };
export const PLACE_KO = {
  Aachen: "아헨", Altona: "알토나", Amsterdam: "암스테르담", Astana: "아스타나", "Bad Elster": "바트엘스터", "Bad Kissingen": "바트키싱겐", "Bad Lauterberg": "바트라우터베르크", "Bad Nauheim": "바트나우하임", "Bad Niendorf": "바트니엔도르프", "Bad Oeynhausen": "바트에인하우젠", "Bad Pistyan": "바트피슈차니",
  "Baden-Baden": "바덴바덴", Baku: "바쿠", Barcelona: "바르셀로나", Barmen: "바르멘", Bazna: "바즈나", Beijing: "베이징", Belfort: "벨포르", Belgrade: "베오그라드", Berlin: "베를린", Bermuda: "버뮤다", Bern: "베른", Beverwijk: "베베르베이크", Biel: "비엘", Bilbao: "빌바오", Birmingham: "버밍엄", Bled: "블레드",
  Bournemouth: "본머스", Bradford: "브래드퍼드", Breslau: "브레슬라우", Bristol: "브리스틀", Brussels: "브뤼셀", Bucharest: "부쿠레슈티", Budapest: "부다페스트", Budva: "부드바", "Buenos Aires": "부에노스아이레스", Bugojno: "부고이노", Caleta: "지브롤터", Cambridge: "케임브리지", Cannes: "칸", Carrasco: "카라스코",
  Chennai: "첸나이", Chicago: "시카고", Cleveland: "클리블랜드", Coburg: "코부르크", Copenhagen: "코펜하겐", Dallas: "댈러스", Debrecen: "데브레첸", Donostia: "산세바스티안", Dortmund: "도르트문트", "Dos Hermanas": "도스에르마나스", Dresden: "드레스덴", Duesseldorf: "뒤셀도르프", Duisburg: "뒤스부르크", Dundee: "던디",
  Elista: "엘리스타", "Enghien les Bains": "앙갱레뱅", Foros: "포로스", Frankfurt: "프랑크푸르트", Geneve: "제네바", Giessen: "기센", Gijon: "히혼", Gjovik: "예비크", Gothenburg: "예테보리", Groningen: "흐로닝언", Haag: "헤이그", Hamburg: "함부르크", Hamilton: "해밀턴", Hannover: "하노버", Hastings: "헤이스팅스",
  Havana: "아바나", Heidelberg: "하이델베르크", Hilversum: "힐베르쉼", Holland: "네덜란드", Hollywood: "할리우드", Homburg: "홈부르크", Hoogeveen: "호헤베인", Jermuk: "제르무크", Johannesburg: "요하네스버그", "Karlovy Vary": "카를로비바리", Karlsbad: "카를스바트", Kecskemet: "케치케메트", Kemeri: "케메리",
  "Khanty-Mansiysk": "한티만시스크", Kiel: "킬", Kiev: "키이우", Koeln: "쾰른", Kosice: "코시체", Krakow: "크라쿠프", Krefeld: "크레펠트", Kuibyshev: "쿠이비셰프", "Lake Hopatcong": "호파트콩 호수", "Las Palmas": "라스팔마스", Leiden: "레이던", Leipzig: "라이프치히", Leningrad: "레닌그라드", Leon: "레온",
  Liege: "리에주", Linares: "리나레스", Ljubljana: "류블랴나", Lodz: "우치", London: "런던", "Los Angeles": "로스앤젤레스", Lugano: "루가노", Lviv: "리비우", Madrid: "마드리드", "Maehrisch Ostrau": "모라비아오스트라바", Magdeburg: "마그데부르크", Manchester: "맨체스터", Manila: "마닐라", Mannheim: "만하임",
  "Mar del Plata": "마르델플라타", Margate: "마게이트", Marienbad: "마리엔바트", Medias: "메디아슈", Meran: "메란", Merano: "메라노", Merida: "메리다", Milan: "밀라노", "Monte Carlo": "몬테카를로", "Montecatini Terme": "몬테카티니테르메", Montevideo: "몬테비데오", Montreal: "몬트리올", Moscow: "모스크바",
  Munich: "뮌헨", Naestved: "네스트베드", Nalchik: "날치크", Nanjing: "난징", Netanya: "네타냐", "New York": "뉴욕", Nice: "니스", Niksic: "니크시치", Noordwijk: "노르트베이크", Nottingham: "노팅엄", Novgorod: "노브고로드", "Novi Sad": "노비사드", Nuremberg: "뉘른베르크", Oslo: "오슬로", Ostende: "오스텐더",
  "Palma de Mallorca": "팔마데마요르카", Pamplona: "팜플로나", Paris: "파리", Parnu: "패르누", Pasadena: "패서디나", Philadelphia: "필라델피아", Podebrady: "포데브라디", Poikovsky: "포이콥스키", "Polanica Zdroj": "폴라니차즈드루이", Prague: "프라하", Ramsgate: "램스게이트", "Reggio Emilia": "레조에밀리아",
  Reykjavik: "레이캬비크", Riga: "리가", "Rogaska Slatina": "로가슈카슬라티나", Rosario: "로사리오", Rotterdam: "로테르담", "Saint Louis": "세인트루이스", Salzburg: "잘츠부르크", "San Antonio": "샌안토니오", "San Remo": "산레모", "San Sebastian": "산세바스티안", "Santa Monica": "산타모니카", Sarajevo: "사라예보",
  Scarborough: "스카버러", Semmering: "젬머링", Shamkir: "샤므키르", Sharjah: "샤르자", Shenzhen: "선전", Skelleftea: "셸레프테오", Skopje: "스코페", Sliac: "슬리아치", Sochi: "소치", Sofia: "소피아", "St Louis": "세인트루이스", "St Petersburg": "상트페테르부르크", Stavanger: "스타방에르", Stepanakert: "스테파나케르트",
  Stockholm: "스톡홀름", Stuttgart: "슈투트가르트", Sverdlovsk: "스베르들롭스크", Swinemuende: "슈비노우이시치에", "Szcawno Zdroj": "슈차브노즈드루이", Tashkent: "타슈켄트", Tbilisi: "트빌리시", Teeside: "티사이드", "Teplitz-Schoenau": "테플리츠쇤아우", "Ter Apel": "테르아펠", Thessaloniki: "테살로니키",
  Tilburg: "틸뷔르흐", Titograd: "티토그라드", "Trencianske Teplice": "트렌친스케테플리체", Triberg: "트리베르크", Turin: "토리노", Ujpest: "우이페슈트", Vienna: "빈", Vilnius: "빌뉴스", Vinkovci: "빈코프치", Vrbas: "브르바스", Waddinxveen: "바딩스베인", Warsaw: "바르샤바", "Wijk aan Zee": "베이크안제이",
  "Bad Harzburg": "바트하르츠부르크", Geneva: "제네바", Zurich: "취리히", Winnipeg: "위니펙", Yerevan: "예레반", Zagreb: "자그레브", Zandvoort: "잔트포르트", Zuerich: "취리히", Zug: "추크",
};

// 개최 도시 → 나라(FIDE 3글자 코드, 모나코·지브롤터는 ISO 2글자) — PGN Site에 나라 코드가 없는 대회의 국기용. 옛 나라(소련·유고·체코슬로바키아)의 도시는 지금의 나라로.
export const PLACE_CC = Object.fromEntries("Aachen GER|Altona GER|Amsterdam NED|Astana KAZ|Bad Elster GER|Bad Kissingen GER|Bad Lauterberg GER|Bad Nauheim GER|Bad Niendorf GER|Bad Oeynhausen GER|Bad Pistyan SVK|Bad Harzburg GER|Baden-Baden GER|Baku AZE|Barcelona ESP|Barmen GER|Bazna ROU|Beijing CHN|Belfort FRA|Belgrade SRB|Berlin GER|Bermuda BER|Bern SUI|Beverwijk NED|Biel SUI|Bilbao ESP|Birmingham ENG|Bled SLO|Bournemouth ENG|Bradford ENG|Breslau POL|Bristol ENG|Brussels BEL|Bucharest ROU|Budapest HUN|Budva MNE|Buenos Aires ARG|Bugojno BIH|Caleta GI|Cambridge ENG|Cannes FRA|Carrasco URU|Chennai IND|Chicago USA|Cleveland USA|Coburg GER|Copenhagen DEN|Dallas USA|Debrecen HUN|Donostia ESP|Dortmund GER|Dos Hermanas ESP|Dresden GER|Duesseldorf GER|Duisburg GER|Dundee SCO|Elista RUS|Enghien les Bains FRA|Foros UKR|Frankfurt GER|Geneva SUI|Geneve SUI|Giessen GER|Gijon ESP|Gjovik NOR|Gothenburg SWE|Groningen NED|Haag NED|Hamburg GER|Hannover GER|Hastings ENG|Havana CUB|Heidelberg GER|Hilversum NED|Holland NED|Hollywood USA|Homburg GER|Hoogeveen NED|Jermuk ARM|Johannesburg RSA|Karlovy Vary CZE|Karlsbad CZE|Kecskemet HUN|Kemeri LAT|Khanty-Mansiysk RUS|Kiel GER|Kiev UKR|Koeln GER|Kosice SVK|Krakow POL|Krefeld GER|Kuibyshev RUS|Lake Hopatcong USA|Las Palmas ESP|Leiden NED|Leipzig GER|Leningrad RUS|Leon ESP|Liege BEL|Linares ESP|Ljubljana SLO|Lodz POL|London ENG|Los Angeles USA|Lugano SUI|Lviv UKR|Madrid ESP|Maehrisch Ostrau CZE|Magdeburg GER|Manchester ENG|Manila PHI|Mannheim GER|Mar del Plata ARG|Margate ENG|Marienbad CZE|Medias ROU|Meran ITA|Merano ITA|Merida ESP|Milan ITA|Monte Carlo MC|Montecatini Terme ITA|Montevideo URU|Montreal CAN|Moscow RUS|Munich GER|Naestved DEN|Nalchik RUS|Nanjing CHN|Netanya ISR|New York USA|Nice FRA|Niksic MNE|Noordwijk NED|Nottingham ENG|Novgorod RUS|Novi Sad SRB|Nuremberg GER|Oslo NOR|Ostende BEL|Palma de Mallorca ESP|Pamplona ESP|Paris FRA|Parnu EST|Pasadena USA|Philadelphia USA|Podebrady CZE|Poikovsky RUS|Polanica Zdroj POL|Prague CZE|Ramsgate ENG|Reggio Emilia ITA|Reykjavik ISL|Riga LAT|Rogaska Slatina SLO|Rosario ARG|Rotterdam NED|Saint Louis USA|Salzburg AUT|San Antonio USA|San Remo ITA|San Sebastian ESP|Santa Monica USA|Sarajevo BIH|Scarborough ENG|Semmering AUT|Shamkir AZE|Sharjah UAE|Shenzhen CHN|Skelleftea SWE|Skopje MKD|Sliac SVK|Sochi RUS|Sofia BUL|St Louis USA|St Petersburg RUS|Stavanger NOR|Stockholm SWE|Stuttgart GER|Sverdlovsk RUS|Swinemuende POL|Szcawno Zdroj POL|Tashkent UZB|Tbilisi GEO|Teeside ENG|Teplitz-Schoenau CZE|Ter Apel NED|Thessaloniki GRE|Thessalonika GRE|Tilburg NED|Titograd MNE|Trencianske Teplice SVK|Triberg GER|Turin ITA|Ujpest HUN|Vienna AUT|Vilnius LTU|Vinkovci CRO|Vrbas SRB|Waddinxveen NED|Warsaw POL|Wijk aan Zee NED|Winnipeg CAN|Yerevan ARM|Zagreb CRO|Zandvoort NED|Zuerich SUI|Zurich SUI|Zug SUI".split("|").map((x) => { const i = x.lastIndexOf(" "); return [x.slice(0, i), x.slice(i + 1)]; }));
// 파일명 접두어(소문자·영문자만)가 도시가 아닌 시리즈
export const SERIES_OVERRIDE = {
  sovietchamp: { name: "USSR Championship", ko: "소련 선수권", type: "historic", place: "various", placeKo: "", cc: "" },
  worldchamp: { name: "World Championship Match", ko: "세계선수권 타이틀전", type: "cycle", place: "various", placeKo: "", cc: "" },
  interzonal: { name: "Interzonal Tournament", ko: "인터존 토너먼트", type: "cycle", place: "various", placeKo: "", cc: "" },
  fidechamp: { name: "FIDE World Championship (Knockout)", ko: "FIDE 세계선수권(녹아웃)", type: "cycle", place: "various", placeKo: "", cc: "" },
  wccqual: { name: "World Championship Qualifier", ko: "세계선수권 예선", type: "cycle", place: "various", placeKo: "", cc: "" },
  pcachamp: { name: "PCA World Championship", ko: "PCA 세계선수권 매치", type: "cycle", place: "various", placeKo: "", cc: "" },
  pcaqual: { name: "PCA Qualifiers", ko: "PCA 예선", type: "cycle", place: "various", placeKo: "", cc: "" },
  pcacand: { name: "PCA Candidates", ko: "PCA 후보자전", type: "cycle", place: "various", placeKo: "", cc: "" },
  gibraltar: { name: "Gibraltar Chess Festival", ko: "지브롤터 체스 페스티벌", place: "Gibraltar", placeKo: "지브롤터", cc: "GIB" },
  ljubojevic: { name: "Portorož–Ljubljana", ko: "포르토로주–류블랴나", place: "Ljubljana", placeKo: "류블랴나", cc: "SLO" },
  karlovy: { name: "Karlovy Vary", ko: "카를로비바리", place: "Karlovy Vary", placeKo: "카를로비바리", cc: "CZE" },
  hague: { name: "The Hague", ko: "헤이그 대회", place: "The Hague", placeKo: "헤이그", cc: "NED" },
  saintlouis: { name: "Saint Louis (US Championship·American Cup)", ko: "세인트루이스(미국 선수권·아메리칸 컵)", place: "Saint Louis", placeKo: "세인트루이스", cc: "USA" },
};
